export default {
  index: {
    fenZhong: '分钟',
    riQi: '日期',
    yueFen: '月份',
    cRONBiao: 'Cron表达式',
    meiNian: '每年',
    meiYue: '每月',
    meiZhou: '每周',
    meiTian: '每天',
    meiXiaoShi: '每小时',
    yue: '月',
    yueMo: '月末',
    hao: '号',
    fen: '分',
    zhouRi: '周日',
    zhouLiu: '周六',
    zhouWu: '周五',
    zhouSi: '周四',
    zhouSan: '周三',
    zhouEr: '周二',
    zhouYi: '周一',
  },
};
