export default {
  otp: {
    guiZeMiaoShu: '규칙 설명: ',
    luoJiGuanXi: '논리 관계: ',
    tiaoJianGuanXi: '조건 관계: ',
    quanZhong: '가중치: ',
    piPeiDu: '일치 점수: ',
    piPeiZiDuan: '일치 필드: ',
    fuHeMingDanLie: '검토 목록: ',
    buCunZai: '포함 안 됨',
    cunZai: '포함됨',
    buWeiKong: 'null 아님',
    weiKong: 'null',
    houZhui: '접미사',
    buBaoHan: '제외',
    qianZhui: '접두사',
    baoHan: '포함',
    bianLiang: '변수',
    changLiang: '상수',
    mo: 't',
    fei: 'n',
    zu: 'g',
    huo: '또는',
    qie: '그리고',
    yu: '그리고',
    wei: '는',
    is: '는',
    zhu: 'g',
    changliang: '상수',
    bianliang: '변수',
    baohan: '포함',
    qianzhui: '접두사',
    buhan: '제외',
    houzhui: '접미사',
    weikong: 'null',
    feikong: 'null아님',
    cunzai: '포함됨',
    bucunzai: '포함안됨',
    fuhe: '검토 목록: ',
    pipei: '일치 필드: ',
    pidu: '일치 점수: ',
    quanzhong: '가중치: ',
    tiaojian: '조건 관계: ',
    luoji: '논리 관계: ',
    guize: '규칙 설명: ',
  },
  utils: {
    liXian: '오프라인',
    shiShi: '실시간',
    ziDuan: '필드',
  },
};
