export const RELATION_WIDTH = 120;
export const COMPONENT_HEIGHT = 40;
export const COMPONENT_WIDTH = 120;
export const COMPONENT_SPACE_VERTICAL = 20;
export const COMPONENT_SPACE_HORIZONTAL = 38;
export const COMPONENT_MARGIN = 5;
export const ROOT_WIDTH = 130;
export const ROOT_HEIGHT = 60;
export const MARGIN_LEFT = 60;
export const CONTENT_WIDTH = 100;
export const DOT_WIDTH = 20;
export const EXPAND_WIDTH = 16;

let constant = {
  RELATION_WIDTH,
  COMPONENT_HEIGHT,
  COMPONENT_WIDTH,
  COMPONENT_SPACE_VERTICAL,
  COMPONENT_SPACE_HORIZONTAL,
  COMPONENT_MARGIN,
  ROOT_HEIGHT,
  MARGIN_LEFT,
  CONTENT_WIDTH,
  DOT_WIDTH,
  EXPAND_WIDTH,
};

export default constant;
