export default {
  authorizesOrgList: '機構列表',
  allOrgAvailable: '全部機構',
  authorizesAppList: '通道列表',
  allAppAvailable: '全部通道',
  authorizesUserList: '使用者列表',
  allUserAvailable: '全部使用者',
  search: '請輸入機構名稱',
  availableOrgs: '可用機構',
  availableApps: '可用通道',
  availableUsers: '可用使用者',
  clear: '清空',
  hasBeenSelected: '已選',
  numOfOrg: '%s 個機構',
  numOfApp: '%s 個通道',
  numOfUser: '%s 個使用者',
  enterAppName: '請輸入通道名稱',
  enterUserName: '請輸入使用者名稱',
};
