export default {
  index: {
    fenZhong: 'Minutes',
    riQi: 'Date',
    yueFen: 'Month',
    meiNian: 'Every year',
    meiYue: 'Monthly',
    meiZhou: 'Every week',
    meiTian: 'Every day',
    meiXiaoShi: 'Per hour',
    yue: 'Month',
    yueMo: 'End of month',
    hao: 'No.',
    fen: 'Points',
    zhouRi: 'Sunday',
    zhouLiu: 'Saturday',
    zhouWu: 'Friday',
    zhouSi: 'Thursday',
    zhouSan: 'Wednesday',
    zhouEr: 'Tuesday',
    zhouYi: 'Monday',
    cRONBiao: 'Cron expression',
  },
};
