export default {
  shanChuDangQianXing: 'Delete current row',
  tianJiaYiXiang: 'Add an item',
  qingXuanZe: 'Please select',
  bianLiang: 'variable',
  changLiang: 'constant',
  qingShuRuChangLiang: 'Please enter constant content',
  yingWenDouHaoFen: 'English comma separated, such as 1,2',
  fouFALS: 'No [false]',
  shiTRUE: 'Yes [true]',
  huo: 'or',
  yu: 'And',
  buPiPei: 'Mismatch',
  piPei: 'matching',
  xiangSiDuBuPi: 'Similarity mismatch',
  xiangSiDuPiPei: 'Similarity match ',
  buDengYu: 'Not equal to',
  dengYu: 'equal to',
  buBaoHan: 'Excluding',
  baoHan: 'contain',
  buCunZaiYu: 'Does not exist in',
  cunZaiYu: 'Exist in',
  buWeiKong: 'Not empty',
  weiKong: 'Is empty',
  xiaoYuDengYu: 'Less than or equal to',
  xiaoYu: 'less than',
  daYuDengYu: 'Greater than or equal to',
  daYu: 'greater than',
  houZhui: 'suffix',
  qianZhui: 'prefix',
};
