export default {
  ruleconditon: {
    tianJiaTiaoJianZu: 'Add Condition Group',
    tianJiaDanTiaoTiao: 'Add a single condition',
    ziDingYi: 'custom',
    yiXiaTiaoJianJun: 'None of the following conditions are met',
    manZuYiXiaRen: 'Meet any of the following conditions',
    manZuYiXiaSuo: 'Meet all of the following conditions',
  },
  constants: {
    buPiPei: 'Mismatch',
    piPei: 'matching',
    xiangSiDuBuPi: 'Similarity mismatch',
    xiangSiDuPiPei: 'Similarity match ',
    buDengYu: 'Not equal to',
    dengYu: 'equal to',
    buBaoHan: 'Excluding',
    baoHan: 'contain',
    buCunZaiYu: 'Does not exist in',
    cunZaiYu: 'Exist in',
    buWeiKong: 'Not empty',
    weiKong: 'Is empty',
    xiaoYuDengYu: 'Less than or equal to',
    xiaoYu: 'less than',
    daYuDengYu: 'Greater than or equal to',
    daYu: 'greater than',
    houZhui: 'suffix',
    qianZhui: 'prefix',
  },
};
