export default {
  ruleconditon: {
    tianJiaTiaoJianZu: '添加条件组',
    tianJiaDanTiaoTiao: '添加单条条件',
    ziDingYi: '自定义',
    yiXiaTiaoJianJun: '以下条件均不满足',
    manZuYiXiaRen: '满足以下任意条件',
    manZuYiXiaSuo: '满足以下所有条件',
  },
  constants: {
    buPiPei: '不匹配',
    piPei: '匹配',
    xiangSiDuBuPi: '相似度不匹配',
    xiangSiDuPiPei: '相似度匹配',
    buDengYu: '不等于',
    dengYu: '等于',
    buBaoHan: '不包含',
    baoHan: '包含',
    buCunZaiYu: '不存在于',
    cunZaiYu: '存在于',
    buWeiKong: '不为空',
    weiKong: '为空',
    xiaoYuDengYu: '小于等于',
    xiaoYu: '小于',
    daYuDengYu: '大于等于',
    daYu: '大于',
    houZhui: '后缀',
    qianZhui: '前缀',
  },
};
