export default {
  otp: {
    guiZeMiaoShu: 'คำอธิบายกฎ: ',
    luoJiGuanXi: 'ความสัมพันธ์เชิงตรรกะ: ',
    tiaoJianGuanXi: 'ความสัมพันธ์เงื่อนไข: ',
    quanZhong: 'น้ำหนัก: ',
    piPeiDu: 'คะแนนการจับคู่: ',
    piPeiZiDuan: 'ฟิลด์ที่ตรงกัน: ',
    fuHeMingDanLie: 'รายการตรวจสอบ: ',
    buCunZai: 'ไม่อยู่ใน',
    cunZai: 'อยู่ใน',
    buWeiKong: 'ไม่เป็นค่าว่าง',
    weiKong: 'เป็นค่าว่าง',
    houZhui: 'ส่วนต่อท้าย',
    buBaoHan: 'ยกเว้น',
    qianZhui: 'คำนำหน้า',
    baoHan: 'รวม',
    bianLiang: 'ตัวแปร',
    changLiang: 'ค่าคงที่',
    mo: 't',
    fei: 'n',
    zu: 'g',
    huo: 'หรือ',
    qie: 'และ',
    yu: 'และ',
    wei: 'คือ',
    is: 'คือ',
    zhu: 'g',
    changliang: 'ค่าคงที่',
    bianliang: 'ตัวแปร',
    baohan: 'รวม',
    qianzhui: 'คำนำหน้า',
    buhan: 'ยกเว้น',
    houzhui: 'ส่วนต่อท้าย',
    weikong: 'เป็นค่าว่าง',
    feikong: 'ไม่ว่าง',
    cunzai: 'อยู่ใน',
    bucunzai: 'ไม่อยู่ใน',
    fuhe: 'รายการตรวจสอบ: ',
    pipei: 'ฟิลด์ที่ตรงกัน: ',
    pidu: 'คะแนนการจับคู่: ',
    quanzhong: 'น้ำหนัก: ',
    tiaojian: 'ความสัมพันธ์เงื่อนไข: ',
    luoji: 'ความสัมพันธ์เชิงตรรกะ: ',
    guize: 'คำอธิบายกฎ: ',
  },
  utils: {
    liXian: 'ออฟไลน์',
    shiShi: 'แบบเรียลไทม์',
    ziDuan: 'ฟิลด์',
  },
};
