export default {
  otp: {
    guiZeMiaoShu: 'Rule Description: ',
    luoJiGuanXi: 'Logic Relationship: ',
    tiaoJianGuanXi: 'Condition Relationship: ',
    quanZhong: 'Weight: ',
    piPeiDu: 'Match Score: ',
    piPeiZiDuan: 'Match Fields: ',
    fuHeMingDanLie: 'Review List: ',
    buCunZai: 'Not In',
    cunZai: 'In',
    buWeiKong: 'Not Null',
    weiKong: 'Is Null',
    houZhui: 'Suffix',
    buBaoHan: 'Exclude',
    qianZhui: 'Prefix',
    baoHan: 'Include',
    bianLiang: 'Variable',
    changLiang: 'Constant',
    zu: 'g',
    is: 'is',
    yu: 'and',
    qie: 'and',
    huo: 'or',
    zhu: 'g',
    fei: 'n',
    mo: 't',
    changliang: 'constant',
    bianliang: 'variable',
    baohan: 'include',
    qianzhui: 'prefix',
    buhan: 'exclude',
    houzhui: 'suffix',
    weikong: 'isnull',
    feikong: 'notnull',
    cunzai: 'in',
    bucunzai: 'notin',
    fuhe: 'Review List',
    pipei: 'Match Fields: ',
    pidu: 'Match Score: ',
    quanzhong: 'Weight: ',
    tiaojian: 'Condition Relationship: ',
    luoji: 'Logic Relationship: ',
    guize: 'Rule Description: ',
  },
  utils: {
    liXian: 'Offline',
    shiShi: 'RealTime',
    ziDuan: 'Field',
  },
};
