export default {
  otp: {
    guiZeMiaoShu: 'Descripción de regla: ',
    luoJiGuanXi: 'Relación lógica: ',
    tiaoJianGuanXi: 'Relación de condición: ',
    quanZhong: 'Peso: ',
    piPeiDu: 'Puntuación de coincidencia: ',
    piPeiZiDuan: 'Campos de coincidencia: ',
    fuHeMingDanLie: 'Lista de revisión: ',
    buCunZai: 'No en',
    cunZai: 'En',
    buWeiKong: 'No nulo',
    weiKong: 'Es nulo',
    houZhui: 'Sufijo',
    buBaoHan: 'Excluir',
    qianZhui: 'Prefijo',
    baoHan: 'Incluir',
    bianLiang: 'Variable',
    changLiang: 'Constante',
    mo: 't',
    fei: 'n',
    zu: 'g',
    huo: 'o',
    qie: 'y',
    yu: 'y',
    wei: 'es',
    is: 'es',
    zhu: 'g',
    changliang: 'constante',
    bianliang: 'variable',
    baohan: 'incluir',
    qianzhui: 'prefijo',
    buhan: 'excluir',
    houzhui: 'sufijo',
    weikong: 'esnulo',
    feikong: 'nonulo',
    cunzai: 'en',
    bucunzai: 'noen',
    fuhe: 'Lista de revisión: ',
    pipei: 'Campos de coincidencia: ',
    pidu: 'Puntuación de coincidencia: ',
    quanzhong: 'Peso: ',
    tiaojian: 'Relación de condición: ',
    luoji: 'Relación lógica: ',
    guize: 'Descripción de regla: ',
  },
  utils: {
    liXian: 'Fuera de línea',
    shiShi: 'Tiempo real',
    ziDuan: 'Campo',
  },
};
