export default {
  otp: {
    guiZeMiaoShu: 'وصف القاعدة: ',
    luoJiGuanXi: 'العلاقة المنطقية: ',
    tiaoJianGuanXi: 'علاقة الشرط: ',
    quanZhong: 'الوزن: ',
    piPeiDu: 'درجة المطابقة: ',
    piPeiZiDuan: 'حقول المطابقة: ',
    fuHeMingDanLie: 'قائمة المراجعة: ',
    buCunZai: 'ليس في',
    cunZai: 'في',
    buWeiKong: 'ليس فارغاً',
    weiKong: 'فارغ',
    houZhui: 'لاحقة',
    buBaoHan: 'استبعاد',
    qianZhui: 'بادئة',
    baoHan: 'تضمين',
    bianLiang: 'متغير',
    changLiang: 'ثابت',
    mo: 't',
    fei: 'n',
    zu: 'g',
    huo: 'أو',
    qie: 'و',
    yu: 'و',
    wei: 'هو',
    is: 'هو',
    zhu: 'g',
    changliang: 'ثابت',
    bianliang: 'متغير',
    baohan: 'تضمين',
    qianzhui: 'بادئة',
    buhan: 'استبعاد',
    houzhui: 'لاحقة',
    weikong: 'فارغ',
    feikong: 'ليسفارغاً',
    cunzai: 'في',
    bucunzai: 'ليسفي',
    fuhe: 'قائمة المراجعة: ',
    pipei: 'حقول المطابقة: ',
    pidu: 'درجة المطابقة: ',
    quanzhong: 'الوزن: ',
    tiaojian: 'علاقة الشرط: ',
    luoji: 'العلاقة المنطقية: ',
    guize: 'وصف القاعدة: ',
  },
  utils: {
    liXian: 'غير متصل',
    shiShi: 'الوقت الفعلي',
    ziDuan: 'حقل',
  },
};
